export enum GlobalActionsEnum {
  TOGGLE_THEME = 'TOGGLE_THEME'
}

export enum Wh00tActionsEnum {
  MINIMIZED_SWITCH = 'MINIMIZED_SWITCH',
  NEW_MESSAGE = 'NEW_MESSAGE',
  HISTORICAL_MESSAGE = 'HISTORICAL_MESSAGE',
  CLEAR_MESSAGES = 'CLEAR_MESSAGES',
  DISCONNECTED = 'DISCONNECTED',
  SECRET_MESSAGE = 'SECRET_MESSAGE',
  INTERNAL_ALERT_ON = 'INTERNAL_ALERT_ON',
  INTERNAL_ALERT_OFF = 'INTERNAL_ALERT_OFF',
  CONNECTED = 'CONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTION_ERROR = 'CONNECTION_ERROR'
}

export enum Wh00tMessageTypeEnum {
  LOCAL = 'LOCAL',
  HISTORY = 'HISTORY',
  SOCKET = 'SOCKET',
}

export enum ThemeModeEnum {
  LIGHT = 'LIGHT',
  DARK = 'DARK'
}

export enum LocalStorageEnum {
  THEME = 'THEME',
  USERNAME ='USERNAME',
  STAY_CONNECTED ='STAY_CONNECTED'
}
