// Organized from https://emojipedia.org/

export const EmojiOptions: { [key: string]: string } = {
  ':smile_cat:': '😸',
  ':thumbsup:': '👍',
  ':thumbsdown:': '👎',
  ':clap:': '👏',
  ':heart:': '❤️',
  ':sparkles:': '✨',
  ':poop:': '💩',
  ':rolling_on_the_floor_laughing:': '🤣',
  ':joy:': '😂',
  ':smiling_face_with_smiling_eyes:': '😊',
  ':slightly_smiling_face:': '🙂',
  ':yum:': '😋',
  ':sweat_smile:': '😅',
  ':innocent:': '😇',
  ':money_mouth_face:': '🤑',
  ':shushing_face:': '🤫',
  ':face_with_hand_over_mouth:': '🤭',
  ':smirk:': '😏',
  ':thinking_face:': '🤔',
  ':neutral_face:': '😐',
  ':face_with_rolling_eyes:': '🙄',
  ':face_with_raised_eyebrow:': '🤨',
  ':sleeping:': '😴',
  ':face_exhaling:': '😮‍💨',
  ':nauseated_face:': '🤢',
  ':cold_face:': '🥶',
  ':hot_face:': '🥵',
  ':cursing_face:': '🤬',
  ':partying_face:': '🥳',
  ':triumph:': '😤',
  ':unamused_face:': '😒',
  ':pleading_face:': '🥺',
  ':face_with_thermometer:': '🤒',
  ':face_with_head_bandage:': '🤕',
  ':face_vomiting:': '🤮',
  ':exploding_head:': '🤯',
  ':tired_face:': '😫',
  ':sob:': '😭',
  ':scream:': '😱',
  ':bow:': '🙇',
  ':pray:': '🙏',
  ':person_facepalming:': '🤦',
  ':brain:': '🧠',
  ':eyes:': '👀',
  ':party_popper:': '🎉',
  ':muscle:': '💪',
  ':snake:': '🐍',
  ':fire:': '🔥',
  ':ghost:': '👻',
  ':skull:': '💀',
  ':skull_and_crossbones:': '☠️',
  ':umbrella:': '☂️',
  ':mushroom:': '🍄',
  ':check_mark_button:': '✅',
};
