// Organized from https://emojipedia.org/

export const EmojiOptions: { [key: string]: string } = {
  ':thumbsup:': '👍',
  ':thumbsdown:': '👎',
  ':clap:': '👏',
  ':heart:': '❤️',
  ':check_mark_button:': '✅',
  ':sparkles:': '✨',

  ':slightly_smiling_face:': '🙂',
  ':grinning_face:': '😀 ',
  ':yum:': '😋',
  ':winking_face:': '😉',
  ':exploding_head:': '🤯',
  ':partying_face:': '🥳',

  ':smiling_face_with_smiling_eyes:': '😊',
  ':rolling_on_the_floor_laughing:': '🤣',
  ':joy:': '😂',
  ':sob:': '😭',
  ':unamused_face:': '😒',
  ':scream:': '😱',

  ':smile_cat:': '😸',
  ':cat_with_tears_of_joy:': '😹',
  ':ghost:': '👻',
  ':crying_cat:': '😿',
  ':pouting_cat:': '😾',
  ':weary_cat:': '🙀',

  ':thinking_face:': '🤔',
  ':neutral_face:': '😐',
  ':face_with_rolling_eyes:': '🙄',
  ':face_with_raised_eyebrow:': '🤨',
  ':face_exhaling:': '😮‍💨',
  ':sleeping:': '😴',

  ':face_with_thermometer:': '🤒',
  ':nauseated_face:': '🤢',
  ':face_vomiting:': '🤮',
  ':cold_face:': '🥶',
  ':hot_face:': '🥵',
  ':pleading_face:': '🥺',

  ':skull:': '💀',
  ':cursing_face:': '🤬',
  ':triumph:': '😤',
  ':tired_face:': '😫',
  ':muscle:': '💪',
  ':snake:': '🐍',

  ':pray:': '🙏',
  ':person_facepalming:': '🤦',
  ':innocent:': '😇',
  ':face_with_hand_over_mouth:': '🤭',
  ':sweat_smile:': '😅',
  ':smirk:': '😏',

  ':alien:': '👽',
  ':roboto:': '🤖',
  ':fox:': '🦊',
  ':laptop:': '💻',
  ':seedling:': '🌱',
  ':hot_beverage:': '☕',

  ':sun:': '☀️',
  ':party_popper:': '🎉',
  ':fire:': '🔥',
  ':rocket:': '🚀',
  ':poop:': '💩',
  ':mushroom:': '🍄',
};
